# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "prepare"
  - "unlink"
  - "infra"
  - "verify"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "kostis-codefresh/terraform-loft"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "main"
    git: "github-1"
    stage: "prepare"

  RemoveVirtualContext:
    image: codefresh/cli
    title: Removing VClusters from Codefresh
    working_directory: "${{clone}}" 
    stage: unlink
    fail_fast: true
    commands:
      - codefresh delete cluster prod-virtual-cluster || true
      - codefresh delete cluster qa-virtual-cluster || true
      - codefresh delete cluster staging-virtual-cluster  || true 
      
  ChooseCluster:
    image: codefresh/kubectl
    title: "Choosing Real cluster"
    working_directory: "${{clone}}" 
    stage: infra
    commands:
      - kubectl config use-context loft-real-cluster
      
      
    

  DestroyWithTerraform:
    image: hashicorp/terraform:1.3.7
    title: "Destroying virtual clusters"
    working_directory: "${{clone}}" 
    stage: infra
    commands:
      - cp -r /codefresh/volume/sensitive/.kube/ ~/.kube 
      - cd give-me-an-app
      - terraform init
      - terraform destroy -auto-approve

  Verify:
    image: ghcr.io/loft-sh/vcluster-cli
    title: "Listing virtual clusters"
    working_directory: "${{clone}}" 
    stage: infra
    commands:
      - vcluster list

 