# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "prepare"
  - "infra"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "kostis-codefresh/terraform-loft"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github-1"
    stage: "prepare"

  ChooseCluster:
    image: codefresh/kubectl
    title: "Choosing Real cluster"
    working_directory: "${{clone}}" 
    stage: prepare
    commands:
      - kubectl config use-context loft-real-cluster

  PlanWithTerraform:
    image: hashicorp/terraform:1.3.7
    title: "Planning virtual clusters"
    working_directory: "${{clone}}" 
    stage: infra
    commands:
      - cp -r /codefresh/volume/sensitive/.kube/ ~/.kube 
      - cd multiple-clusters-remote
      - terraform init
      - terraform plan



